### PR TITLE
Multichain Provider

### LINKED ISSUE #1653: Multichain Provider
(part of https://github.com/oceanprotocol/pm/issues/185)

Make sure that chainId is available when provider cannot figure it out.
Provider will choose the corresponding web3 object based on chainId

This affects code in https://github.com/oceanprotocol/ocean.js/blob/main/src/services/Provider.ts.

Provider calls that need to be updated:
 - /api/services/encrypt  - add chainId , in case Provider has different privateKeys per each chain

Provider calls that do not need updates:
 - /api/services/initialize  - no need, provider will take chainId by resolving DID
 - /api/services/download - no need, provider will take chainId by resolving DID
- /api/services/fileinfo - no need, provider will take chainId by resolving DID if DID is passed, otherwise it's just a Files object
- POST /api/services/compute - - no need, provider will take chainId by resolving each DID (algo, datasets, etc)

- [ ] Add integration tests for the multichain provider
- [ ] By using this barge branch: https://github.com/oceanprotocol/barge/pull/348 let's add a test for publish the asset, edit the metadata service and then consume the asset.

### PR DESCRIPTION
**Pull request by jamiehewitt15**
Fixes #1653 

Changes proposed in this PR:

- Adding `chainId` as a param to provider encrypt post request

### CODE REVIEW

**Comment by kremalicious** [comment]
are we touching all the provider URIs in the `ConfigHelper` or is that for another PR?

**Comment by jamiehewitt15** [comment]
> are we touching all the provider URIs in the `ConfigHelper` or is that for another PR?

It can be done here, I didn't see anywhere that we've documented what the new URI will be, I guess `https://v4.provider.oceanprotocol.com` is a reasonable assumption?

**Comment by jamiehewitt15** [comment]
So it seems that there isn't a decision yet on what the domain will be. There isn't anything more that can be done on this until we have more progress on https://github.com/oceanprotocol/provider/issues/572 so I've added the blocked label for now.

**Comment by bogdanfazakas** [comment]
closing this, handled in #1698

**Pull request closed without merging**
