### PR TITLE
add new status structure

### PR DESCRIPTION
**Pull request by kremalicious**
This implements OEP-8 changes in data structure for the `curation` object.

See https://github.com/oceanprotocol/OEPs/pull/236

### CODE REVIEW

**Comment by kremalicious** [comment]
as far as I see we also need to update `plecos` https://github.com/oceanprotocol/plecos/blob/develop/plecos/schemas/metadata_remote_v0_5.json#L467-L517

Because `curation` now becomes what we always called local metadata, meaning editable by user/publisher as opposed to remote meaning updated by Aquarius alone.

**Comment by alexcos20** [comment]
issue already there:  https://github.com/oceanprotocol/plecos/issues/45

**Comment by jamiehewitt15** [comment]
From @alexcos20's message on the OEP issue, `curation` needs to be changed to `status` 

https://github.com/oceanprotocol/OEPs/pull/236#issuecomment-836580582

**Comment by jamiehewitt15** [comment]
@kremalicious I have changed 'Curation' to 'Status' according to this: https://github.com/oceanprotocol/OEPs/pull/236#issuecomment-836580582 

Is there much else that needs to be done on this? It is currently blocking:  https://github.com/oceanprotocol/ocean.js/pull/786

**Comment by mihaisc** [comment]
looks good

**Comment by jamiehewitt15** [comment]
Is this still blocked?

**Comment by alexcos20** [comment]
@kremalicious - all changes are already in #786, so we can close this

**Pull request closed without merging**
