### PR TITLE
Issue-#1313: Update beginners guide for v4

### LINKED ISSUE #1313: Update beginners guide for v4
**Is your feature request related to a problem? Please describe.**
Update `beginners_guide.md` for v4.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by akshay-ap**
Fixes #1313

Changes proposed in this PR:

- Update beginners_guide.md file

### CODE REVIEW

**Comment by AnaLoznianu** [comment]
@bogdanfazakas @kremalicious @mihaisc @miquelcabot @alexcos20 Can you please review this PR? Thank you

**Comment by kremalicious** [comment]
sorry, review is not happening anytime soon from my side as it requires going through all those code examples and actually executing them locally, and then maintain them all while we are still doing major ocean.js updates.

After this project here reaches 1.0.0 happy to revisit

**Comment by AnaLoznianu** [comment]
@miquelcabot @jamiehewitt15 @akshay-ap I think we can close this as we have this PR ready: https://github.com/oceanprotocol/ocean.js/pull/1438 which takes a different approach to the READMEs

**Comment by jamiehewitt15** [comment]
The new plan is to reduce the ocean.js documentation down to one readme and one code examples file (possibly split into two when we add compute to data) as described [here](https://github.com/oceanprotocol/ocean.js/issues/1354#issuecomment-1112032587)

**Pull request closed without merging**
