### PR TITLE
Building CommonJS, ES and UMD modules with microbundle

### PR DESCRIPTION
**Pull request by jamiehewitt15**
Closes: https://github.com/oceanprotocol/ocean.js/issues/246

Changes proposed in this PR:
- Implementing a new build process with microbundle

### CODE REVIEW

**Comment by alexcos20** [comment]
awesome !
@kremalicious @mihaisc - can we check the frontend ?

**Comment by mihaisc** [comment]
Will do

**Comment by jamiehewitt15** [comment]
By the way, `microbundle` gives the option of optimizing the build for either a node or web environment (the default is web), so I have also added in an extra script `build:node` for optimizing for a node environment

**Comment by mihaisc** [comment]
I keep getting these, not sure yet what the problem is. In theory `utils` and `ConfigHelper` are exported 
image

**Comment by jamiehewitt15** [comment]
Hmm ok that's odd, how can I replicated that? It all seems to work when running `npm run build` in the terminal

**Comment by jamiehewitt15** [comment]
Thanks

**Comment by jamiehewitt15** [comment]
@mihaisc @kremalicious do you have any idea what the problem here could be? I have played around quite a bit with the settings of microbundle (there aren't that many) any it doesn't seem to make any difference. I'm thinking I'll try with a different bundler

**Comment by jamiehewitt15** [comment]
I've started looking into doing this with [rollup](https://rollupjs.org/) on a separate branch but so far there are still issues: https://github.com/oceanprotocol/ocean.js/pull/703

**Comment by jamiehewitt15** [comment]
I figure out the issue with this, there are two problems:
1. `microbundle` bundles everything into one index.js file. While, within the market, there are many imports from the files within the `/utils` folder. 
2. `microbundle` only bundles up the modules that are actually used within ocean.js. So  for example, `ConfigHelperConfig` is defined and exported but never actually used anywhere so it gets ignored by `microbundle` and isn't included in the bundled up index.js file. 

If we want to use `microbundle` on it's own we would need to refactor the code in ocean.js and ocean market (changing the imports from `'@oceanprotocol/lib/dist/node/utils/'` to `'@oceanprotocol/lib'`). 

For the moment, I have got this working with ocean market by using both `tsc` and `microbundle`

**Comment by jamiehewitt15** [comment]
I have refactored the market code so that there are no imports from the utils folder: https://github.com/oceanprotocol/market/pull/481

There is still the issue that some exports are not included in the bundle:

>     2. `microbundle` only bundles up the modules that are actually used within ocean.js. So  for example, `ConfigHelperConfig` is defined and exported but never actually used anywhere so it gets ignored by `microbundle` and isn't included in the bundled up index.js file.

This issue applies to:
`ConfigHelperConfig`
`ConfigHelperNetworkId`
`ConfigHelperNetworkName`
`LogLevel`

I'll work next on refactoring the ocean.js code to make sure all of the exports are included in the bundle.

**Comment by jamiehewitt15** [comment]
This needs to be merged at the same time as the refactoring of the `/utils` imports in Ocean Market: https://github.com/oceanprotocol/market/pull/481

I have tested this in Ocean Market (using `npm link` and then building and running it) and it seems to all wok ok

**Comment by mihaisc** [comment]
Tested it with the market pr and it works ok

**Review by mihaisc — APPROVED** [review]

**Pull request merged**
