### PR TITLE
Remove checks from publishing. ADded chain ID check for ordering.

### LINKED ISSUE #1876: Add checks for chainID at ordering level
Add checks for chainID at ordering level.
Update the check for chainID when publishing a ddo, validate first if the chainID exists in the JSON after do the check, if the chainID is not provided in the JSON, then do nothing, because the SDK puts automatically the chain ID.

### PR DESCRIPTION
**Pull request by mariacarmina**
Fixes #1876  .

Changes proposed in this PR:

- added new 2 keys for DDO type which are used by ocean-cli https://github.com/oceanprotocol/ocean-cli/pull/73/files#diff-f91e67e39398317c3ef27ae0a3d66d6bc56f8a9561f8d14f9f7301b44427d9ddR46
- remove checks regarding chain id and did when publishing asset from samples
- add checks for chain id when ordering asset.

### CODE REVIEW

**Comment by jamiehewitt15** [comment]
What issue is this fixing?

**Comment by mariacarmina** [comment]
> What issue is this fixing?

It is not defined, I can create an issue for this PR, it was dicussed to add the chain ID checks for publishing and for ordering level.

**Review by paulo-ocean — APPROVED** [review]
lgtm

**Review by jamiehewitt15 — APPROVED** [review]
Looks good to me

**Pull request merged**
