### PR TITLE
Add remove ocean liquidity function

### LINKED ISSUE #684: Remove ocean liquidity
We need another function similar to `removeOceanLiquidity` with the following params :
``` 
account: string,
poolAddress: string,
poolShares: string,
minimumOceanReceived: string
```
This function probably needs to use `exitswapPoolAmountIn` instead of `exitswapPoolAmountOut`

### PR DESCRIPTION
**Pull request by mihaisc**
Closes #684 
Suggestions for the function name are appreciated

### CODE REVIEW

**Comment by kremalicious** [comment]
not fully sure about the implications but feels like we could make `removeOceanLiquidityWithMinimum` the new `removeOceanLiquidity`. I don't see a reason why `removePoolLiquidity` & `removeOceanLiquidity` should be so different, and seems what is in `removeOceanLiquidityWithMinimum` would make it consistent.

If we go with additional method, then we should Mae distinction between `removePoolLiquidity`/`removeOceanLiquidity`/`removeOceanLiquidityWithMinimum` also more clear in the JSDoc description, e.g. add `..., based on minimum amount of OCEAN to receive.`

**Comment by mihaisc** [comment]
I agree that the current one doesn't suit any need. I opt for replacing it. @alexcos20 will this impact anything? From my knowledge this was made for the market more or less.

**Comment by alexcos20** [comment]
Only market is using that, as far as I know.  Unless we have some other devs using ocean.js..

**Comment by mihaisc** [comment]
So... do we all agree to change `removeOceanLiquidity` and `removeDTLiquidity` to accept `minOcean` and `minDt` instead of `maximumPoolShares` ?

**Comment by alexcos20** [comment]
I would keep them both, because they have different usage

**Review by alexcos20 — APPROVED** [review]

**Pull request merged**
