### PR TITLE
logs/history speed optimizations

### PR DESCRIPTION
**Pull request by alexcos20**
pool logs/history should be much faster.

- added startBlock in the config, so we can narrow the blocks range searched
- lots of parallelization

### CODE REVIEW

**Comment by kremalicious** [comment]
testing this locally against local market and does not really load faster for me. But see the config changed so we might need to have more changes in react or market somewhere

**Comment by alexcos20** [comment]
do you use a custom config or you are just calling getConfig('mainnet') ?

**Comment by mihaisc** [comment]
The config is just passed to ocean lib in react, so no changes needed there

**Comment by alexcos20** [comment]
@kremalicious @mihaisc - check this new improvement

**Comment by mihaisc** [comment]
I get a lot of nulls from `tokens` , i added `if (tokens != null)` before `for`, not sure if this is ok.
 https://github.com/oceanprotocol/ocean.js/blob/1d717cb3b03b150d16bb684bd13a1d7bdafa55a6/src/balancer/OceanPool.ts#L174

**Comment by mihaisc** [comment]
Isn't this redundant and costly, since in market at least we already know the dt address
https://github.com/oceanprotocol/ocean.js/blob/1d717cb3b03b150d16bb684bd13a1d7bdafa55a6/src/balancer/OceanPool.ts#L889

**Comment by kremalicious** [comment]
This makes the loading time for the pool transactions table go from 4 min. down to 5 sec. for me. SHIP IT

sorcery

**Review by kremalicious — APPROVED** [review]

**Comment by alexcos20** [comment]
have some worries that infura limits the number of requests to 10/s, so doing all that in parallel might brake something.

but let's try it :)

**Comment by kremalicious** [comment]
so we have between 100-300 concurrent users at all times on the frontend during a typical day now. So we really should look into what happens when infura fails. Once we announce this, people will flock to their history page

**Comment by mihaisc** [comment]
But these calls are made on client right? So it has no impact on our infura account

**Pull request merged**
