### PR TITLE
Feature/compute nextv

### LINKED ISSUE #613: Compute-to-Data: Remote Algorithms & multiple access inputs

### PR DESCRIPTION
**Pull request by alexcos20**
Breaking changes !!
 - removed ocean.compute.order  and replace it with ocean.compute.orderAsset and ocean.compute.orderAlgorithm

New features:
1. additional datasets for compute jobs
2. supports datasets & algos published by other providers

closes #613 and #572

Status: testing with new provider, will merge it once we release that

### CODE REVIEW

**Comment by alexcos20** [comment]
still blocked by provider

**Comment by alexcos20** [comment]
once the new provider is released, I will update barge and merge this

**Comment by 0x3bfc** [comment]
that looks a fat PR ... Is there anyway to start review it ?

**Comment by mihaisc** [comment]
Will this break non-compute functionalities? Because the compute ones we will test them anyway when we implement compute in the market

**Comment by alexcos20** [comment]
> Will this break non-compute functionalities? Because the compute ones we will test them anyway when we implement compute in the market

no, beside compute, there are only small tweaks to provider.ts and WebServiceConnector , but no breaking change

**Review by mihaisc — APPROVED** [review]

**Pull request merged**
