### PR TITLE
Feature/travis dockerhub auth

### PR DESCRIPTION
**Pull request by alexcos20**
We need to test if this affects PR's opened from forked repos.

### CODE REVIEW

**Comment by alexcos20** [comment]
all fine, I added a check condition

**Comment by kremalicious** [comment]
Usual tactic to make fork builds succeed is to condition ally run those jobs/commands which require env vars. As for barge, pulling images should still succeed for forks within the anonymous tier on DockerHub, right? Unless we have many fork builds at once I guess.

If we're into optimizing for forks, then another candidate is `CC_TEST_REPORTER_ID` where when it is not present no coverage reporting should be tried to send, so this line: https://github.com/oceanprotocol/ocean.js/blob/feature/travis_dockerhub_auth/.travis.yml#L44

**Comment by alexcos20** [comment]
that why we have the env check before docker login:
if [[ -n "$DOCKERHUB_PASSWORD" && -n "$DOCKERHUB_USERNAME" ]]; then echo "logining in to docker";echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin;fi

if DOCKERHUB_USERNAME & DOCKERHUB_PASSWORD are not exported by travis  (they are not exported for external PR), we will not do any auth and barge will download the images as anonymous

**Comment by alexcos20** [comment]
added a check for  CC_TEST_REPORTER_ID too

**Review by kremalicious — APPROVED** [review]
[that warning sounds frightening](https://travis-ci.com/github/oceanprotocol/ocean.js/builds/217471344#L284) but I guess we can live with that

**Pull request merged**
