### PR TITLE
Add ocean-contracts artifacts in root dir

### PR DESCRIPTION
**Pull request by bogdanfazakas**
Fixes # .

Changes proposed in this PR:

- add artifacts folder with the used artifacts from ocean-contracts in the root folder
- update imports artifacts import  
- removed not used dependancies

### CODE REVIEW

**Comment by bogdanfazakas** [comment]
Moved the artifacts in the src folder, if i have them in root folder the build fails because we have tsconfig rootDir pointing to src folder. Trying fix that locally and update the pr later if i succed but wanted to have this green till then

**Comment by mihaisc** [comment]
i don't think we need the .dbg files , am i wrong @alexcos20

**Comment by bogdanfazakas** [comment]
> i don't think we need the .dbg files , am i wrong @alexcos20

we don't use them so i guess we do not need them

**Comment by bogdanfazakas** [comment]
> Moved the artifacts in the src folder, if i have them in root folder the build fails because we have tsconfig rootDir pointing to src folder. Trying fix that locally and update the pr later if i succed but wanted to have this green till then

should be fine now updated the config file

**Comment by bogdanfazakas** [comment]
> Please move https://github.com/oceanprotocol/contracts/blob/v4main_postaudit/addresses/address.json here as well, it can be somewhere in src

it was added in the artifacts folder, just updated it with latest changes made by @alexcos20 , should i move it to src folder or we can have it here in the artifacts folder?

**Comment by mihaisc** [comment]
leave it

**Comment by alexcos20** [comment]
> i don't think we need the .dbg files , am i wrong @alexcos20

no, .dgb files are only for hardhat debugs

**Review by alexcos20 — APPROVED** [review]
nice to have dbg files removed before merge

**Review by mihaisc — APPROVED** [review]

**Pull request merged**
