### PR TITLE
refactor typedoc generation

### PR DESCRIPTION
**Pull request by kremalicious**
TypeDoc v0.20.0 came with breaking changes, but simplifies a lot of things so we do not have to create our own TypeDoc app to generate the json anymore.

Also results in a way smaller json file so we can highly reduce how we read that out over in the docs. Part fo solving https://github.com/oceanprotocol/docs/issues/527

- refactor typedoc.js to generate initial json with default command, spawned as child process
- merge `src/lib.ts` & `src/index.ts`, leaving only `src/index.ts`

### CODE REVIEW

**Comment by kremalicious** [comment]
new format generated with this change confirmed to be working in https://github.com/oceanprotocol/docs/pull/546: https://docs-git-fix-typedoc.oceanprotocol.vercel.app/references/ocean.js

**Review by 0x3bfc — APPROVED** [review]
LGTM

**Comment by 0x3bfc** [comment]
sorry didn't see it is in draft

**Comment by kremalicious** [comment]
not gonna happen now but can inform how we do it in new ocean.js, if at all

**Pull request closed without merging**
